// Generated by https://quicktype.io

export interface NoticiaResponse {
  id:                number;
  titulo:            string;
  contenido:         string;
  imagenUrl:         string;
  fechaPublicacion:  Date;
  activo:            boolean;
  usuarioId:         number;
  fechaCreacion:     Date;
  fechaModificacion: null;
  usuario:           null;
}
