// Generated by https://quicktype.io

export interface ReservaResponse {
  id?: number;
  usuarioId: number;
  recursoId: number;
  fecha: Date | string;
  horaInicio: string;
  horaFin: string;
  motivo: string;
  estado?: string;
  activo?: boolean;
  fechaCreacion?: Date | string;
  fechaModificacion?: Date | string;
  recurso?: null;
  usuario?: null;
}

// Generated by https://quicktype.io

export interface ReservaFullResponse {
  id: number;
  usuarioId: number;
  recursoId: number;
  fecha: Date;
  horaInicio: string;
  horaFin: string;
  motivo: string;
  estado: Estado;
  activo: boolean;
  fechaCreacion: Date;
  fechaModificacion: Date;
  nombreVecino: string;
  cedula: string;
  email: string;
  nombreRecurso: string;
  imagenUrl: string;
  tipoRecursoId: number;
}

export type Estado = 'Aprobada' | 'Pendiente' | 'Rechazada';
